import { AddressCreateNestedManyWithoutUsersInput } from "./AddressCreateNestedManyWithoutUsersInput";
import { DocumentCreateNestedManyWithoutUsersInput } from "./DocumentCreateNestedManyWithoutUsersInput";
import { InstitutionWhereUniqueInput } from "../institution/InstitutionWhereUniqueInput";
import { PersonalIdInfoWhereUniqueInput } from "../personalIdInfo/PersonalIdInfoWhereUniqueInput";
import { InputJsonValue } from "../../types";

export type UserCreateInput = {
  addressDetails?: string | null;
  addresses?: AddressCreateNestedManyWithoutUsersInput;
  birthDate?: string | null;
  dateOfBirth?: string | null;
  documentDetails?: string | null;
  documents?: DocumentCreateNestedManyWithoutUsersInput;
  email?: string | null;
  emailAddress?: string | null;
  emailAddressOtp?: string | null;
  emailOtp?: string | null;
  firstName?: string | null;
  gender?: "Option1" | null;
  institution?: InstitutionWhereUniqueInput | null;
  lastName?: string | null;
  mobilePhone?: number | null;
  mobilePhoneNumber?: number | null;
  otpExpires?: Date | null;
  otpExpiry?: Date | null;
  password: string;
  personalIdInfo?: PersonalIdInfoWhereUniqueInput | null;
  personalIdInformation?: string | null;
  phoneOtp?: string | null;
  relatedInstitution?: string | null;
  roles: InputJsonValue;
  smsOtp?: string | null;
  userCategory?: "Option1" | null;
  username: string;
  userType?: "Option1" | null;
};
