/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsString,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumPersonalIdInfoPersonalIdType } from "./EnumPersonalIdInfoPersonalIdType";
import { UserCreateNestedManyWithoutPersonalIdInfosInput } from "./UserCreateNestedManyWithoutPersonalIdInfosInput";
import { Type } from "class-transformer";

@InputType()
class PersonalIdInfoCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  businessPhone?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  jobTitle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nationality?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  personalIdNumber?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumPersonalIdInfoPersonalIdType,
  })
  @IsEnum(EnumPersonalIdInfoPersonalIdType)
  @IsOptional()
  @Field(() => EnumPersonalIdInfoPersonalIdType, {
    nullable: true,
  })
  personalIdType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortJobTitle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  uploadIdDocs?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutPersonalIdInfosInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutPersonalIdInfosInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutPersonalIdInfosInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutPersonalIdInfosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  voterId?: string | null;
}

export { PersonalIdInfoCreateInput as PersonalIdInfoCreateInput };
