/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PersonalIdInfoService } from "../personalIdInfo.service";
import { PersonalIdInfoCreateInput } from "./PersonalIdInfoCreateInput";
import { PersonalIdInfo } from "./PersonalIdInfo";
import { PersonalIdInfoFindManyArgs } from "./PersonalIdInfoFindManyArgs";
import { PersonalIdInfoWhereUniqueInput } from "./PersonalIdInfoWhereUniqueInput";
import { PersonalIdInfoUpdateInput } from "./PersonalIdInfoUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class PersonalIdInfoControllerBase {
  constructor(protected readonly service: PersonalIdInfoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalIdInfo })
  async createPersonalIdInfo(
    @common.Body() data: PersonalIdInfoCreateInput
  ): Promise<PersonalIdInfo> {
    return await this.service.createPersonalIdInfo({
      data: data,
      select: {
        businessPhone: true,
        createdAt: true,
        id: true,
        jobTitle: true,
        nationality: true,
        personalIdNumber: true,
        personalIdType: true,
        shortJobTitle: true,
        updatedAt: true,
        uploadIdDocs: true,
        voterId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalIdInfo] })
  @ApiNestedQuery(PersonalIdInfoFindManyArgs)
  async personalIdInfos(
    @common.Req() request: Request
  ): Promise<PersonalIdInfo[]> {
    const args = plainToClass(PersonalIdInfoFindManyArgs, request.query);
    return this.service.personalIdInfos({
      ...args,
      select: {
        businessPhone: true,
        createdAt: true,
        id: true,
        jobTitle: true,
        nationality: true,
        personalIdNumber: true,
        personalIdType: true,
        shortJobTitle: true,
        updatedAt: true,
        uploadIdDocs: true,
        voterId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalIdInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async personalIdInfo(
    @common.Param() params: PersonalIdInfoWhereUniqueInput
  ): Promise<PersonalIdInfo | null> {
    const result = await this.service.personalIdInfo({
      where: params,
      select: {
        businessPhone: true,
        createdAt: true,
        id: true,
        jobTitle: true,
        nationality: true,
        personalIdNumber: true,
        personalIdType: true,
        shortJobTitle: true,
        updatedAt: true,
        uploadIdDocs: true,
        voterId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalIdInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePersonalIdInfo(
    @common.Param() params: PersonalIdInfoWhereUniqueInput,
    @common.Body() data: PersonalIdInfoUpdateInput
  ): Promise<PersonalIdInfo | null> {
    try {
      return await this.service.updatePersonalIdInfo({
        where: params,
        data: data,
        select: {
          businessPhone: true,
          createdAt: true,
          id: true,
          jobTitle: true,
          nationality: true,
          personalIdNumber: true,
          personalIdType: true,
          shortJobTitle: true,
          updatedAt: true,
          uploadIdDocs: true,
          voterId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalIdInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePersonalIdInfo(
    @common.Param() params: PersonalIdInfoWhereUniqueInput
  ): Promise<PersonalIdInfo | null> {
    try {
      return await this.service.deletePersonalIdInfo({
        where: params,
        select: {
          businessPhone: true,
          createdAt: true,
          id: true,
          jobTitle: true,
          nationality: true,
          personalIdNumber: true,
          personalIdType: true,
          shortJobTitle: true,
          updatedAt: true,
          uploadIdDocs: true,
          voterId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: PersonalIdInfoWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        addressDetails: true,
        birthDate: true,
        createdAt: true,
        dateOfBirth: true,
        documentDetails: true,
        email: true,
        emailAddress: true,
        emailAddressOtp: true,
        emailOtp: true,
        firstName: true,
        gender: true,
        id: true,

        institution: {
          select: {
            id: true,
          },
        },

        lastName: true,
        mobilePhone: true,
        mobilePhoneNumber: true,
        otpExpires: true,
        otpExpiry: true,

        personalIdInfo: {
          select: {
            id: true,
          },
        },

        personalIdInformation: true,
        phoneOtp: true,
        relatedInstitution: true,
        roles: true,
        smsOtp: true,
        updatedAt: true,
        userCategory: true,
        username: true,
        userType: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: PersonalIdInfoWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updatePersonalIdInfo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: PersonalIdInfoWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updatePersonalIdInfo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: PersonalIdInfoWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updatePersonalIdInfo({
      where: params,
      data,
      select: { id: true },
    });
  }
}
